webpack_encore:
    # The path where Encore is building the assets - i.e. Encore.setOutputPath()
    output_path: '%kernel.project_dir%/public/build'
    
    # If multiple builds are defined (as shown below), you can disable the default build:
    # output_path: false
    
    # Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: true
    # link_attributes:
    
    # If using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    # crossorigin: 'anonymous'
    
    # Preload all rendered script and link tags automatically via the HTTP/2 Link header
    # preload: true
    
    # Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
    # strict_mode: false
    
    # If you have multiple builds:
    # builds:
        # frontend: '%kernel.project_dir%/public/frontend/build'
    
    # Pass your server config here if you want to use webpack-dev-server
    # dev_server:
    #     path: '%kernel.project_dir%/public/build'
